<a href="https://colab.research.google.com/github/kondratyukkatya9-ML/ML_home_work/blob/main/Copy_of_HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [18]:
vector = np.random.rand(10)
print(vector)
vector.shape

[0.58199731 0.80873161 0.78455077 0.57253755 0.80096845 0.19799998
 0.47076565 0.62436156 0.61603602 0.95377904]


(10,)

In [5]:
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
print(matrix)
matrix.shape

[[11 14 17]
 [20 23 26]
 [29 32 35]]


(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [19]:
vector_rounded = np.round(vector + 10, 2)
print(vector_rounded)

[10.58 10.81 10.78 10.57 10.8  10.2  10.47 10.62 10.62 10.95]


In [7]:
matrix_multiply = matrix*2
print(matrix_multiply)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [20]:
vector_squared = vector ** 2
print(vector_squared)

[0.33872087 0.65404682 0.61551992 0.32779924 0.64155046 0.03920399
 0.22162029 0.38982736 0.37950038 0.90969446]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [8]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = B @ A   # це мені LLM сказав, що є такий оператор матричного множення "@""
print(result_matrix)
result_matrix.shape

[[0.7281 0.5202]
 [0.2034 0.2846]]


(2, 2)

In [12]:
result_matrix = np.dot(B, A) # матричне множення, як в лекційному ноутбуці ;)
print(result_matrix)
result_matrix.shape

[[0.7281 0.5202]
 [0.2034 0.2846]]


(2, 2)

2. Отримаємо розмірність (2, 1)

In [13]:
result_vector = result_matrix @ C
print(result_vector)
result_vector.shape

[[0.5202]
 [0.2846]]


(2, 1)

3. Отримаємо матрицю розмірністю (2, 2)

In [14]:
result_matrix_D = result_matrix @ D
print(result_matrix_D)
result_matrix_D.shape

[[0.5202 0.7281]
 [0.2846 0.2034]]


(2, 2)


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [16]:
result_matrix_T = result_matrix.T
print(result_matrix_T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [28]:
vector_T = vector.T
print(vector_T) #нічого не змінилось, транспонування не виконується над однорозмірним масивом
vector_T.shape

[0.58199731 0.80873161 0.78455077 0.57253755 0.80096845 0.19799998
 0.47076565 0.62436156 0.61603602 0.95377904]


(10,)

In [30]:
print(vector)
vector.shape

[0.58199731 0.80873161 0.78455077 0.57253755 0.80096845 0.19799998
 0.47076565 0.62436156 0.61603602 0.95377904]


(10,)

In [24]:
column_vector = np.expand_dims(vector, axis=1)
print(column_vector)
column_vector.shape

[[0.58199731]
 [0.80873161]
 [0.78455077]
 [0.57253755]
 [0.80096845]
 [0.19799998]
 [0.47076565]
 [0.62436156]
 [0.61603602]
 [0.95377904]]


(10, 1)

In [31]:
column_vector_T = column_vector.T
print(column_vector_T)
column_vector_T.shape

[[0.58199731 0.80873161 0.78455077 0.57253755 0.80096845 0.19799998
  0.47076565 0.62436156 0.61603602 0.95377904]]


(1, 10)